/**
 * scenarioI18n.js — ترجمة محتوى السيناريوهات (40 سيناريو)
 * العربية هي المصدر الأساسي، والإنجليزية/العبرية ترجمات ثابتة.
 * يُستخدم مع scenarios.js — كل سيناريو يُترجم: title, desc, objective,
 * objectives[], hints[], expected, time, checks[].label
 */
import { getLang } from "./i18n";

const I18N = {
  /* ══════════ مبتدئ (Beginner) ══════════ */
  first_lan: {
    en: { title: "First LAN", desc: "Build your first network: a switch connecting two PCs that communicate through it.", objective: "Understand basic network components and star topology.", objectives: ["Add a main switch", "Add two PCs", "Connect both PCs to the switch", "Send a ping between them"], hints: ["The switch connects devices in a star topology", "Each device needs a cable to the switch"], expected: "A small star network: switch + two PCs connected to it.", time: "10 min", checks: ["Switch exists", "Two PCs exist", "Switch is connected", "Devices connected (2+ links)"] },
    he: { title: "רשת מקומית ראשונה", desc: "בנו את הרשת הראשונה: מתג המחבר שני מחשבים המתקשרים דרכו.", objective: "הבנת רכיבי רשת בסיסיים וטופולוגיית כוכב.", objectives: ["הוסיפו מתג ראשי", "הוסיפו שני מחשבים", "חברו את שני המחשבים למתג", "שלחו ping ביניהם"], hints: ["המתג מחבר מכשירים בטופולוגיית כוכב", "כל מכשיר זקוק לכבל למתג"], expected: "רשת כוכב קטנה: מתג + שני מחשבים מחוברים אליו.", time: "10 דקות", checks: ["מתג קיים", "שני מחשבים קיימים", "המתג מחובר", "מכשירים מחוברים (2+ קישורים)"] },
  },
  client_server: {
    en: { title: "Client-Server Model", desc: "Create a Client-Server network: a central server serving client devices.", objective: "Distinguish P2P from Client-Server model practically.", objectives: ["Add a Server", "Add a switch", "Add two PCs as clients", "Connect all to the switch"], hints: ["The server provides the service, the client requests it", "All devices connect through the switch"], expected: "Server + switch + two clients connected via switch.", time: "12 min", checks: ["Server exists", "Switch exists", "Two clients (PC)", "Server connected to network", "Clients connected to switch"] },
    he: { title: "מודל לקוח-שרת", desc: "צרו רשת לקוח-שרת: שרת מרכזי המשרת מכשירי לקוח.", objective: "הבחנה בין P2P למודל לקוח-שרת באופן מעשי.", objectives: ["הוסיפו שרת", "הוסיפו מתג", "הוסיפו שני מחשבים כלקוחות", "חברו הכל למתג"], hints: ["השרת מספק את השירות, הלקוח מבקש אותו", "כל המכשירים מתחברים דרך המתג"], expected: "שרת + מתג + שני לקוחות מחוברים דרך המתג.", time: "12 דקות", checks: ["שרת קיים", "מתג קיים", "שני לקוחות (PC)", "שרת מחובר לרשת", "לקוחות מחוברים למתג"] },
  },
  two_pc_direct: {
    en: { title: "Direct PC-to-PC Connection", desc: "Like in Packet Tracer: two PCs connected directly with a Crossover cable, then ping.", objective: "Master the first steps: drag devices, select cable, connect ports, test.", objectives: ["Add two PCs", "Connect them with a direct cable", "Send ping from one to the other"], hints: ["PC to PC uses a Crossover cable", "No intermediary needed between two devices only"], expected: "Two PCs connected directly to each other.", time: "8 min", checks: ["Two PCs exist", "Direct connection between them"] },
    he: { title: "חיבור ישיר בין מחשבים", desc: "כמו ב-Packet Tracer: שני מחשבים מחוברים ישירות בכבל Crossover ואז ping.", objective: "שליטה בצעדים הראשונים: גרירת מכשירים, בחירת כבל, חיבור יציאות, בדיקה.", objectives: ["הוסיפו שני מחשבים", "חברו אותם בכבל ישיר", "שלחו ping מאחד לשני"], hints: ["PC ל-PC משתמש בכבל Crossover", "אין צורך במתווך בין שני מכשירים בלבד"], expected: "שני מחשבים מחוברים ישירות זה לזה.", time: "8 דקות", checks: ["שני מחשבים קיימים", "חיבור ישיר ביניהם"] },
  },
  console_access: {
    en: { title: "Console Access to a Device", desc: "Prepare a router and a management PC connected via the management port.", objective: "Understand device access methods (Console / Telnet / SSH).", objectives: ["Add a Router", "Add a management PC", "Connect the PC to the router (management cable)"], hints: ["Console is the direct physical connection for initial setup", "Connect PC directly to the Router"], expected: "A router connected to a management PC for setup.", time: "10 min", checks: ["Router exists", "Management PC exists", "PC connected to router"] },
    he: { title: "גישת Console למכשיר", desc: "הכינו נתב ומחשב ניהול המחובר דרך יציאת הניהול.", objective: "הבנת שיטות גישה למכשיר רשת (Console / Telnet / SSH).", objectives: ["הוסיפו נתב", "הוסיפו מחשב ניהול", "חברו את המחשב לנתב (כבל ניהול)"], hints: ["Console הוא החיבור הפיזי הישיר להגדרה ראשונית", "חברו PC ישירות לנתב"], expected: "נתב מחובר למחשב ניהול למשימת הגדרה.", time: "10 דקות", checks: ["נתב קיים", "מחשב ניהול (PC)", "PC מחובר לנתב"] },
  },
  initial_device_config: {
    en: { title: "Initial Device Configuration", desc: "Prepare a management network: router + switch + management PC, all connected.", objective: "Apply the initial setup sequence and save configurations.", objectives: ["Add Router, Switch, and PC", "Connect PC to the switch", "Connect switch to the router"], hints: ["The switch distributes connections to devices", "The router connects the network to the outside world"], expected: "A connected chain: PC → Switch → Router.", time: "15 min", checks: ["Router + Switch + PC", "PC connected to switch", "Switch connected to router"] },
    he: { title: "הגדרות ראשוניות למכשיר", desc: "הכינו רשת ניהול: נתב + מתג + מחשב ניהול, הכל מחובר.", objective: "יישום רצף ההגדרה הראשונית ושמירת ההגדרות.", objectives: ["הוסיפו נתב, מתג ו-PC", "חברו PC למתג", "חברו מתג לנתב"], hints: ["המתג מחלק חיבורים למכשירים", "הנתב מחבר את הרשת לעולם החיצוני"], expected: "שרשרת מחוברת: PC ← מתג ← נתב.", time: "15 דקות", checks: ["נתב + מתג + PC", "PC מחובר למתג", "מתג מחובר לנתב"] },
  },
  layer_stack: {
    en: { title: "Encapsulation Path Through Layers", desc: "Build a complete path from a user device to the Internet passing through all layers.", objective: "Reinforce the OSI model practically: physical → data link → network → application.", objectives: ["Add PC (application layer)", "Add Switch (data link layer)", "Add Router (network layer)", "Add Cloud (Internet)", "Connect the full chain"], hints: ["Data is encapsulated with a header at each layer", "Path: PC → Switch → Router → Cloud"], expected: "A complete connected chain PC → Switch → Router → Cloud.", time: "15 min", checks: ["PC + Switch + Router + Cloud", "PC connected to switch", "Switch connected to router", "Router connected to Internet (Cloud)"] },
    he: { title: "נתיב אנקפסולציה דרך השכבות", desc: "בנו נתיב מלא ממכשיר משתמש לאינטרנט העובר דרך כל השכבות.", objective: "חיזוק מודל OSI באופן מעשי: פיזית ← קישור ← רשת ← יישום.", objectives: ["הוסיפו PC (שכבת יישום)", "הוסיפו מתג (שכבת קישור)", "הוסיפו נתב (שכבת רשת)", "הוסיפו Cloud (אינטרנט)", "חברו את השרשרת המלאה"], hints: ["נתונים מוקפסים עם כותרת בכל שכבה", "הנתיב: PC ← מתג ← נתב ← Cloud"], expected: "שרשרת מלאה מחוברת PC ← מתג ← נתב ← Cloud.", time: "15 דקות", checks: ["PC + מתג + נתב + Cloud", "PC מחובר למתג", "מתג מחובר לנתב", "נתב מחובר לאינטרנט (Cloud)"] },
  },

  /* ══════════ سهل (Easy) ══════════ */
  cable_lab: {
    en: { title: "Cables and Ports Lab", desc: "Connect 3 PCs to a switch with appropriate Straight-Through cables.", objective: "Select the correct cable between devices and understand Auto-MDIX.", objectives: ["Add a switch", "Add 3 PCs", "Connect each device to the switch with the right cable"], hints: ["PC to Switch = Straight-Through", "Check port compatibility before confirming"], expected: "A switch with 3 ports occupied by PCs.", time: "12 min", checks: ["Switch exists", "3 PCs", "All devices connected", "Connection via switch"] },
    he: { title: "מעבדת כבלים ויציאות", desc: "חברו 3 מחשבים למתג עם כבלי Straight-Through מתאימים.", objective: "בחירת הכבל הנכון בין מכשירים והבנת Auto-MDIX.", objectives: ["הוסיפו מתג", "הוסיפו 3 מחשבים", "חברו כל מכשיר למתג בכבל מתאים"], hints: ["PC למתג = Straight-Through", "בדקו תאימות יציאות לפני אישור"], expected: "מתג עם 3 יציאות תפוסות במחשבים.", time: "12 דקות", checks: ["מתג קיים", "3 מחשבים", "כל המכשירים מחוברים", "חיבור דרך המתג"] },
  },
  subnet_basics: {
    en: { title: "Basic IP Addressing", desc: "Set up a properly addressed network: two devices on the same network passing through a gateway router.", objective: "Understand the network portion and host portion of an IPv4 address and the default gateway.", objectives: ["Add a switch and two PCs", "Add a router as gateway", "Connect the network to the gateway"], hints: ["Devices on the same network use the same mask", "The default gateway is on the router"], expected: "A local network with a gateway router ready.", time: "15 min", checks: ["Switch + two PCs", "Gateway router exists", "Devices connected to switch", "Switch connected to router"] },
    he: { title: "כתובת IP בסיסית", desc: "הקימו רשת עם כתובות תקינות: שני מכשירים באותה רשת דרך נתב שער.", objective: "הבנת חלק הרשת וחלק המארח בכתובת IPv4 ושער ברירת המחדל.", objectives: ["הוסיפו מתג ושני מחשבים", "הוסיפו נתב כשער", "חברו את הרשת לשער"], hints: ["מכשירים באותה רשת משתמשים באותו מסכה", "שער ברירת המחדל נמצא על הנתב"], expected: "רשת מקומית עם נתב שער מוכן.", time: "15 דקות", checks: ["מתג + שני מחשבים", "נתב שער קיים", "מכשירים מחוברים למתג", "מתג מחובר לנתב"] },
  },
  frame_flow: {
    en: { title: "Frame Flow Between Switches", desc: "Two switches each connecting its devices — connect them with a shared link.", objective: "Understand frame construction and transfer between switches.", objectives: ["Add two switches", "Connect a PC to each switch", "Connect the two switches together"], hints: ["Each frame carries source MAC and destination MAC", "The link between switches extends the broadcast domain"], expected: "Two connected switches, each with a PC.", time: "12 min", checks: ["Two switches", "Two PCs", "Switches interconnected", "Each switch has a device"] },
    he: { title: "זרימת פריימים בין מתגים", desc: "שני מתגים שכל אחד מחבר את המכשירים שלו — חברו אותם בקישור משותף.", objective: "הבנת בניית פריימים והעברתם בין מתגים.", objectives: ["הוסיפו שני מתגים", "חברו PC לכל מתג", "חברו את שני המתגים יחד"], hints: ["כל פריים נושא MAC מקור ו-MAC יעד", "הקישור בין מתגים מרחיב את תחום השידור"], expected: "שני מתגים מחוברים, ועל כל אחד מחשב.", time: "12 דקות", checks: ["שני מתגים", "שני מחשבים", "מתגים מחוברים", "כל מתג מחובר למכשיר"] },
  },
  mac_learning: {
    en: { title: "Learning MAC Addresses", desc: "Connect 3 devices to a single switch and watch how the MAC table is learned.", objective: "Understand the switch's learning mechanism and frame forwarding.", objectives: ["Add a switch", "Add 3 PCs", "Connect all devices", "Send packets between devices"], hints: ["The switch stores source MAC with its port", "Sending a packet forces the switch to learn"], expected: "A switch with 3 connected PCs and a learning MAC table.", time: "10 min", checks: ["Switch exists", "3 PCs", "All devices connected to switch"] },
    he: { title: "למידת כתובות MAC", desc: "חברו 3 מכשירים למתג אחד וצפו כיצד טבלת MAC נלמדת.", objective: "הבנת מנגנון הלמידה של המתג והעברת פריימים.", objectives: ["הוסיפו מתג", "הוסיפו 3 מחשבים", "חברו את כל המכשירים", "שלחו חבילות בין המכשירים"], hints: ["המתג שומר MAC מקור עם היציאה שלו", "שליחת חבילה מכריחה את המתג ללמוד"], expected: "מתג עם 3 מחשבים מחוברים וטבלת MAC לומדת.", time: "10 דקות", checks: ["מתג קיים", "3 מחשבים", "כל המכשירים מחוברים למתג"] },
  },
  gateway_setup: {
    en: { title: "Default Gateway Setup", desc: "Two separate networks with two switches, connected by a router as gateway.", objective: "Understand when a host sends a packet to the default gateway.", objectives: ["Add two switches", "Connect a PC to each switch", "Add a router and connect it to both switches"], hints: ["Different network destination → send to gateway", "The router has an interface in each network"], expected: "Two networks connected via a shared router.", time: "15 min", checks: ["Two switches", "Two PCs", "Router connected to both switches", "Devices connected to switches"] },
    he: { title: "הגדרת שער ברירת מחדל", desc: "שתי רשתות נפרדות עם שני מתגים, המחוברות על ידי נתב כשער.", objective: "הבנה מתי מארח שולח חבילה לשער ברירת המחדל.", objectives: ["הוסיפו שני מתגים", "חברו PC לכל מתג", "הוסיפו נתב וחברו אותו לשני המתגים"], hints: ["יעד ברשת אחרת ← שלח לשער", "לנתב יש ממשק בכל רשת"], expected: "שתי רשתות מחוברות דרך נתב משותף.", time: "15 דקות", checks: ["שני מתגים", "שני מחשבים", "נתב מחובר לשני המתגים", "מכשירים מחוברים למתגים"] },
  },
  arp_same_net: {
    en: { title: "Address Resolution in the Same Network", desc: "Two devices on the same network: connect them and watch the ARP broadcast request.", objective: "Understand the ARP sequence: Broadcast for request, Unicast for reply.", objectives: ["Add a switch and two PCs", "Connect both PCs to the switch", "Send ping and watch ARP"], hints: ["ARP Request is broadcast to all", "The reply is Unicast to the asker only"], expected: "Two devices connected via a switch on the same network.", time: "10 min", checks: ["Switch + two PCs", "Both PCs connected to switch"] },
    he: { title: "פענוח כתובות באותה רשת", desc: "שני מכשירים באותה רשת: חברו אותם וצפו בבקשת ARP השידור.", objective: "הבנת רצף ARP: שידור לבקשה, Unicast לתגובה.", objectives: ["הוסיפו מתג ושני מחשבים", "חברו את שני המחשבים למתג", "שלחו ping וצפו ב-ARP"], hints: ["ARP Request נשלח בשידור לכולם", "התגובה נשלחת Unicast לשואל בלבד"], expected: "שני מכשירים מחוברים דרך מתג באותה רשת.", time: "10 דקות", checks: ["מתג + שני מחשבים", "שני המחשבים מחוברים למתג"] },
  },
  ping_path: {
    en: { title: "Ping Path to the Internet", desc: "Build a sequential test path: PC → Switch → Router → Cloud as in Ping tests.", objective: "Master sequential connectivity tests (Local → Gateway → Internet).", objectives: ["Add PC, switch, router, and Cloud", "Connect the chain from PC to Internet", "Send ICMP along the path"], hints: ["Test loopback first, then gateway, then Internet", "Traceroute uses increasing TTL"], expected: "A complete ICMP path from the device to the Internet.", time: "15 min", checks: ["Full chain (PC+Switch+Router+Cloud)", "PC connected to switch", "Switch connected to router", "Router connected to Internet"] },
    he: { title: "נתיב Ping לאינטרנט", desc: "בנו נתיב בדיקה עוקב: PC ← מתג ← נתב ← Cloud כמו בבדיקות Ping.", objective: "שליטה בבדיקות חיבור עוקבות (מקומי ← שער ← אינטרנט).", objectives: ["הוסיפו PC, מתג, נתב ו-Cloud", "חברו את השרשרת מ-PC עד האינטרנט", "שלחו ICMP בנתיב"], hints: ["בדקו תחילה loopback ואז שער ואז אינטרנט", "Traceroute משתמש ב-TTL עולה"], expected: "נתיב ICMP מלא מהמכשיר עד האינטרנט.", time: "15 דקות", checks: ["שרשרת מלאה (PC+מתג+נתב+Cloud)", "PC מחובר למתג", "מתג מחובר לנתב", "נתב מחובר לאינטרנט"] },
  },
  router_first_config: {
    en: { title: "First Router Configuration", desc: "Prepare a router serving two networks: two switches connected to it with devices on each.", objective: "Apply interface configuration (no shutdown) and connect two networks with one router.", objectives: ["Add a Router", "Add two switches and connect each to the router", "Add a PC in each network", "Verify interfaces"], hints: ["Each router interface serves a different network", "no shutdown is essential to activate the interface"], expected: "A router connecting two local networks via two active interfaces.", time: "20 min", checks: ["Router exists", "Two switches", "Router connected to both switches", "A device in each network"] },
    he: { title: "הגדרת נתב ראשונה", desc: "הכינו נתב המשרת שתי רשתות: שני מתגים מחוברים אליו עם מכשירים בכל אחד.", objective: "יישום הגדרת ממשקים (no shutdown) וחיבור שתי רשתות בנתב אחד.", objectives: ["הוסיפו נתב", "הוסיפו שני מתגים וחברו כל מתג לנתב", "הוסיפו PC בכל רשת", "אמתו את הממשקים"], hints: ["כל ממשק נתב משרת רשת אחרת", "no shutdown חיוני להפעלת הממשק"], expected: "נתב המחבר שתי רשתות מקומיות דרך שני ממשקים פעילים.", time: "20 דקות", checks: ["נתב קיים", "שני מתגים", "נתב מחובר לשני המתגים", "מכשיר בכל רשת"] },
  },

  /* ══════════ متوسط (Medium) ══════════ */
  vlan_setup: {
    en: { title: "Basic VLAN Setup", desc: "Create two isolated VLANs on the same switch and verify isolation.", objective: "Logically divide the switch into VLANs with Access ports.", objectives: ["Add a main switch", "Connect 4 PCs (two per VLAN)", "Assign ports to VLAN10 and VLAN20", "Verify group isolation"], hints: ["Define VLAN on the switch first", "Use Access Mode for device ports", "No communication between VLANs without a router"], expected: "A switch with VLAN10 and VLAN20 fully isolated.", time: "15 min", checks: ["Switch exists", "4 PCs", "Enough connections (4+)", "All devices bound"] },
    he: { title: "הגדרת VLAN בסיסית", desc: "צרו שני VLAN מבודדים על אותו מתג ואמתו בידוד.", objective: "חלוקה לוגית של המתג ל-VLAN עם יציאות Access.", objectives: ["הוסיפו מתג ראשי", "חברו 4 מחשבים (שניים לכל VLAN)", "חלקו יציאות ל-VLAN10 ו-VLAN20", "אמתו בידוד בין הקבוצות"], hints: ["הגדירו VLAN על המתג תחילה", "השתמשו ב-Access Mode ליציאות מכשירים", "אין תקשורת בין VLAN ללא נתב"], expected: "מתג עם VLAN10 ו-VLAN20 מבודדים לחלוטין.", time: "15 דקות", checks: ["מתג קיים", "4 מחשבים", "מספיק חיבורים (4+)", "כל המכשירים מחוברים"] },
  },
  vtp_trunk: {
    en: { title: "Trunk Link Between Switches", desc: "Two switches exchanging VLANs over a single Trunk port between them.", objective: "Understand Trunk port and passing multiple VLANs over one link.", objectives: ["Add two switches", "Connect them with a Trunk link", "Add a device on each switch", "Verify VLANs pass through the link"], hints: ["Trunk passes all allowed VLANs", "The other port for inter-switch is Access"], expected: "A Trunk link connecting two switches with devices on each.", time: "20 min", checks: ["Two switches", "Link between switches", "A device on each switch"] },
    he: { title: "קישור Trunk בין מתגים", desc: "שני מתגים המחליפים VLAN דרך יציאת Trunk אחת ביניהם.", objective: "הבנת יציאת Trunk והעברת VLAN מרובים על קישור אחד.", objectives: ["הוסיפו שני מתגים", "חברו ביניהם בקישור Trunk", "הוסיפו מכשיר על כל מתג", "אמתו מעבר VLAN דרך הקישור"], hints: ["Trunk מעביר את כל ה-VLAN המורשים", "היציאה השנייה לחיבור בין מתגים היא Access"], expected: "קישור Trunk המחבר שני מתגים עם מכשירים על כל אחד.", time: "20 דקות", checks: ["שני מתגים", "קישור בין המתגים", "מכשיר על כל מתג"] },
  },
  inter_vlan_roas: {
    en: { title: "Inter-VLAN Routing (Router-on-a-Stick)", desc: "Connect a single router to a Trunk switch to route multiple VLAN traffic.", objective: "Implement Inter-VLAN Routing with sub-interfaces.", objectives: ["Add Router and Switch", "Connect router to switch with a Trunk link", "Add 4 devices (2 per VLAN)", "Test access between groups"], hints: ["A sub-interface per VLAN with dot1Q", "no shutdown on the main interface", "Switch sets its port as Trunk toward the router"], expected: "A router routing between VLAN10 and VLAN20 over a single link.", time: "25 min", checks: ["Router + Switch", "Router connected to switch", "4 PCs", "Devices connected to switch"] },
    he: { title: "ניתוב Inter-VLAN (Router-on-a-Stick)", desc: "חברו נתב אחד למתג Trunk לניתוב תעבורת VLAN מרובה.", objective: "יישום ניתוב Inter-VLAN עם תתי-ממשקים.", objectives: ["הוסיפו נתב ומתג", "חברו נתב למתג בקישור Trunk", "הוסיפו 4 מכשירים (2 לכל VLAN)", "בדקו גישה בין הקבוצות"], hints: ["תת-ממשק לכל VLAN עם dot1Q", "no shutdown על הממשק הראשי", "המתג מגדיר יציאתו כ-Trunk כלפי הנתב"], expected: "נתב המנתב בין VLAN10 ל-VLAN20 דרך קישור אחד.", time: "25 דקות", checks: ["נתב + מתג", "נתב מחובר למתג", "4 מחשבים", "מכשירים מחוברים למתג"] },
  },
  dhcp_fix: {
    en: { title: "Fixing a DHCP Problem", desc: "The network doesn't distribute IP addresses automatically — discover and fix the issue.", objective: "Diagnose and fix DHCP service: server, pool, gateway.", objectives: ["Add a DHCP Server", "Connect the server to the switch", "Verify the distribution pool", "Test devices receiving addresses"], hints: ["DHCP server needs a static IP", "Check Default Gateway in the Pool", "The range must match the network"], expected: "A connected server distributing IP addresses automatically to clients.", time: "25 min", checks: ["DHCP Server exists", "Server connected to network", "Switch for distribution", "Two+ clients"] },
    he: { title: "תיקון בעיית DHCP", desc: "הרשת לא מחלקת כתובות IP אוטומטית — גלו ותקנו את התקלה.", objective: "אבחון ותיקון שירות DHCP: שרת, טווח, שער.", objectives: ["הוסיפו שרת DHCP", "חברו את השרת למתג", "אמתו את טווח החלוקה (Pool)", "בדקו שמכשירים מקבלים כתובות"], hints: ["שרת DHCP זקוק ל-IP קבוע", "בדקו Default Gateway ב-Pool", "הטווח חייב להתאים לרשת"], expected: "שרת מחובר המחלק כתובות IP אוטומטית ללקוחות.", time: "25 דקות", checks: ["שרת DHCP קיים", "השרת מחובר לרשת", "מתג לחלוקה", "שני לקוחות ומעלה"] },
  },
  dhcp_relay: {
    en: { title: "DHCP Across Networks (Relay)", desc: "A DHCP server on a remote network — connect it to clients via a router and helper-address.", objective: "Understand DHCP Relay and converting broadcast to Unicast across the router.", objectives: ["Add a Server in the server network", "Add a router connecting the two networks", "Add a switch and clients", "Enable ip helper-address toward the server"], hints: ["Broadcast doesn't cross the router — that's where Relay comes in", "helper-address directs DHCP requests to the server"], expected: "A DHCP server serving clients on another network via a router.", time: "25 min", checks: ["Server exists", "Router connecting networks", "Server connected to router", "Clients connected (PC)"] },
    he: { title: "DHCP בין רשתות (Relay)", desc: "שרת DHCP ברשת מרוחקת — חברו אותו ללקוחות דרך נתב ו-helper-address.", objective: "הבנת DHCP Relay והמרת שידור ל-Unicast דרך הנתב.", objectives: ["הוסיפו שרת ברשת השרתים", "הוסיפו נתב המחבר את שתי הרשתות", "הוסיפו מתג ולקוחות", "הפעילו ip helper-address לשרת"], hints: ["שידור לא חוצה נתב — כאן נכנס ה-Relay", "helper-address מפנה בקשות DHCP לשרת"], expected: "שרת DHCP המשרת לקוחות ברשת אחרת דרך נתב.", time: "25 דקות", checks: ["שרת קיים", "נתב מחבר רשתות", "שרת מחובר לנתב", "לקוחות מחוברים (PC)"] },
  },
  port_security: {
    en: { title: "Securing Switch Ports", desc: "Close unused ports and enable Port Security on device ports.", objective: "Apply Port Security: MAC limits and violation mode.", objectives: ["Add a switch and 3 PCs", "Connect devices to secured ports", "Enable Sticky MAC", "Re-enable a closed port"], hints: ["maximum 1 per device port", "Shutdown mode closes the port on violation", "no shutdown re-enables the port"], expected: "A switch with secured ports allowing one device per port.", time: "20 min", checks: ["Switch exists", "3 PCs", "All devices connected", "Enough connections (3+)"] },
    he: { title: "אבטחת יציאות מתג", desc: "סגרו יציאות לא בשימוש והפעילו Port Security על יציאות מכשירים.", objective: "יישום Port Security: מגבלות MAC ומצב הפרה.", objectives: ["הוסיפו מתג ו-3 מחשבים", "חברו מכשירים ליציאות מאובטחות", "הפעילו Sticky MAC", "הפעילו מחדש יציאה סגורה"], hints: ["maximum 1 לכל יציאת מכשיר", "מצב Shutdown סוגר יציאה בעת הפרה", "no shutdown מפעיל יציאה מחדש"], expected: "מתג עם יציאות מאובטחות המאפשר מכשיר אחד לכל יציאה.", time: "20 דקות", checks: ["מתג קיים", "3 מחשבים", "כל המכשירים מחוברים", "מספיק חיבורים (3+)"] },
  },
  wifi_network: {
    en: { title: "Office Wi-Fi Network", desc: "Create a wireless network with full coverage and WPA2 security.", objective: "Understand WLAN components: access point, router, 802.11 standards.", objectives: ["Add a Router connected to the Internet (Cloud)", "Add an Access Point", "Connect the AP to the router", "Add 3 laptops", "Verify full coverage"], hints: ["The access point mediates between router and wireless devices", "Place the AP at the center of coverage", "WEP is deprecated — use WPA2 or newer"], expected: "A complete wireless network: router + AP + laptops connected to the Internet.", time: "20 min", checks: ["Router exists", "Access Point exists", "Connected to Internet (Cloud)", "3 laptops", "AP connected to network"] },
    he: { title: "רשת Wi-Fi למשרד", desc: "צרו רשת אלחוטית עם כיסוי מלא ואבטחת WPA2.", objective: "הבנת רכיבי WLAN: נקודת גישה, נתב, תקני 802.11.", objectives: ["הוסיפו נתב מחובר לאינטרנט (Cloud)", "הוסיפו נקודת גישה", "חברו את ה-AP לנתב", "הוסיפו 3 מחשבים ניידים", "אמתו כיסוי מלא"], hints: ["נקודת הגישה מתווכת בין הנתב למכשירים אלחוטיים", "מקמו את ה-AP במרכז הכיסוי", "WEP מיושן — השתמשו ב-WPA2 ומעלה"], expected: "רשת אלחוטית מלאה: נתב + AP + מחשבים ניידים מחוברים לאינטרנט.", time: "20 דקות", checks: ["נתב קיים", "נקודת גישה קיימת", "מחובר לאינטרנט (Cloud)", "3 מחשבים ניידים", "AP מחובר לרשת"] },
  },
  wireless_office: {
    en: { title: "Wireless Router Setup", desc: "An office with two wireless networks: a central router followed by two access points.", objective: "Manage wireless networks: SSID, channels, and Mesh linking.", objectives: ["Add a Router and connect it to the Internet (Cloud)", "Add two Access Points", "Connect APs to the router", "Add two laptops for users", "Set non-overlapping channels (1/6/11)"], hints: ["Channels 1, 6, and 11 are non-overlapping in 2.4GHz", "Mesh extends coverage automatically"], expected: "A dual-AP office wireless network with extended coverage.", time: "25 min", checks: ["Router + Cloud", "Two access points", "Router connected to Internet", "APs connected to router", "Laptops for users"] },
    he: { title: "הגדרת נתב אלחוטי", desc: "משרד עם שתי רשתות אלחוטיות: נתב מרכזי ואחריו שתי נקודות גישה.", objective: "ניהול רשתות אלחוטיות: SSID, ערוצים, וחיבור Mesh.", objectives: ["הוסיפו נתב וחברו אותו לאינטרנט (Cloud)", "הוסיפו שתי נקודות גישה (AP)", "חברו AP לנתב", "הוסיפו שני מחשבים ניידים", "הגדירו ערוצים לא חופפים (1/6/11)"], hints: ["ערוצים 1, 6 ו-11 לא חופפים ב-2.4GHz", "Mesh מרחיב כיסוי אוטומטית"], expected: "רשת משרד אלחוטית כפולת AP עם כיסוי מורחב.", time: "25 דקות", checks: ["נתב + Cloud", "שתי נקודות גישה", "נתב מחובר לאינטרנט", "AP מחוברים לנתב", "מחשבים ניידים למשתמשים"] },
  },
  subnet_plan: {
    en: { title: "Subnet Planning", desc: "Divide 192.168.1.0/24 into two /26 networks and connect them via two routers.", objective: "Apply Subnetting and distribute ranges across two real networks.", objectives: ["Add two routers and connect them", "Add a switch for each router", "Add two devices in each network", "Distribute /26 ranges correctly"], hints: ["/26 = mask 255.255.255.192 and 62 hosts", "First network 192.168.1.0, second 192.168.1.64"], expected: "Two /26 subnetted networks connected via two routers.", time: "30 min", checks: ["Two routers linked", "A switch per network", "4 devices (2 per network)", "Complete network (6+ elements)"] },
    he: { title: "תכנון חלוקת רשתות", desc: "חלקו 192.168.1.0/24 לשתי רשתות /26 וחברו אותן דרך שני נתבים.", objective: "יישום Subnetting וחלוקת טווחים על שתי רשתות ממשיות.", objectives: ["הוסיפו שני נתבים וחברו אותם", "הוסיפו מתג לכל נתב", "הוסיפו שני מכשירים בכל רשת", "חלקו טווחי /26 נכון"], hints: ["/26 = מסכה 255.255.255.192 ו-62 מארחים", "הרשת הראשונה 192.168.1.0, השנייה 192.168.1.64"], expected: "שתי רשתות /26 מחולקות המחוברות דרך שני נתבים.", time: "30 דקות", checks: ["שני נתבים מחוברים", "מתג לכל רשת", "4 מכשירים (2 לכל רשת)", "רשת מלאה (6+ רכיבים)"] },
  },
  broadcast_boundaries: {
    en: { title: "Broadcast Domain Boundaries", desc: "Show how a router splits the broadcast domain: two networks with separate broadcasts.", objective: "Distinguish between broadcast domain and collision domain using real devices.", objectives: ["Add a router", "Add two switches (one per interface)", "Add two devices per switch", "Test broadcast within each network"], hints: ["A single switch is one broadcast domain", "The router doesn't pass broadcasts between its interfaces"], expected: "A router separating two independent broadcast domains.", time: "20 min", checks: ["Router + two switches", "4 PCs", "Router connected to both switches", "Devices connected to switches"] },
    he: { title: "גבולות תחום שידור", desc: "הראו כיצד נתב מפצל את תחום השידור: שתי רשתות עם שידור נפרד.", objective: "הבחנה בין תחום שידור לתחום התנגשות באמצעות מכשירים אמיתיים.", objectives: ["הוסיפו נתב", "הוסיפו שני מתגים (אחד לכל ממשק)", "הוסיפו שני מכשירים לכל מתג", "בדקו שידור בכל רשת"], hints: ["מתג אחד הוא תחום שידור אחד", "הנתב לא מעביר שידור בין הממשקים שלו"], expected: "נתב המפריד שני תחומי שידור עצמאיים.", time: "20 דקות", checks: ["נתב + שני מתגים", "4 מחשבים", "נתב מחובר לשני המתגים", "מכשירים מחוברים למתגים"] },
  },
  tcp_services: {
    en: { title: "Enterprise TCP Services", desc: "A server providing connection-oriented services (HTTP/SSH) to three clients.", objective: "Understand TCP and connection-oriented (Three-Way Handshake) via real services.", objectives: ["Add a Server", "Add a switch and 3 PCs", "Connect all", "Open an HTTP session from a client to the server"], hints: ["HTTP on port 80 and SSH on 22 — both TCP", "Connection starts with SYN and ends with ACK"], expected: "A services server connected to three clients via a switch.", time: "15 min", checks: ["Server exists", "3 clients", "Server connected", "Clients connected"] },
    he: { title: "שירותי TCP לארגון", desc: "שרת המספק שירותים מונחי חיבור (HTTP/SSH) לשלושה לקוחות.", objective: "הבנת TCP וחיבור מונחה (Three-Way Handshake) דרך שירותים ממשיים.", objectives: ["הוסיפו שרת", "הוסיפו מתג ו-3 מחשבים", "חברו הכל", "פתחו חיבור HTTP מלקוח לשרת"], hints: ["HTTP ביציאה 80 ו-SSH ב-22 — שניהם TCP", "החיבור מתחיל ב-SYN ומסתיים ב-ACK"], expected: "שרת שירותים מחובר לשלושה לקוחות דרך מתג.", time: "15 דקות", checks: ["שרת קיים", "3 לקוחות", "שרת מחובר", "לקוחות מחוברים"] },
  },
  app_protocols: {
    en: { title: "Server Farm", desc: "Three servers (web, DHCP/DNS, mail) serving clients via a single switch.", objective: "Run application layer protocols: HTTP, DNS, DHCP, and SMTP.", objectives: ["Add 3 servers", "Add a switch and two clients", "Connect all servers", "Test DNS and HTTP from a client"], hints: ["DNS resolves the name to IP before HTTP", "DHCP uses UDP 67/68", "SMTP for sending mail on port 25"], expected: "Three service servers connected to clients via a central switch.", time: "25 min", checks: ["3 servers", "Central switch", "All servers connected", "Two+ clients"] },
    he: { title: "חוות שרתים", desc: "שלושה שרתים (ווב, DHCP/DNS, דואר) המשרתים לקוחות דרך מתג אחד.", objective: "הפעלת פרוטוקולי שכבת יישומים: HTTP, DNS, DHCP ו-SMTP.", objectives: ["הוסיפו 3 שרתים", "הוסיפו מתג ושני לקוחות", "חברו את כל השרתים", "בדקו DNS ו-HTTP מלקוח"], hints: ["DNS ממיר שם ל-IP לפני HTTP", "DHCP עובד ב-UDP 67/68", "SMTP לשליחת דואר ביציאה 25"], expected: "שלושה שרתי שירות מחוברים ללקוחות דרך מתג מרכזי.", time: "25 דקות", checks: ["3 שרתים", "מתג מרכזי", "כל השרתים מחוברים", "שני לקוחות ומעלה"] },
  },
  ssh_hardening: {
    en: { title: "Securing Access with SSH", desc: "Prepare a management device that reaches the network via SSH only — no Telnet.", objective: "Apply SSH: RSA keys, local user, and transport input ssh.", objectives: ["Add Router, Switch, and management PC", "Connect all", "Enable SSH on the router", "Test access from the PC"], hints: ["SSH needs hostname, domain-name, and RSA keys", "transport input ssh prevents Telnet", "SSH is encrypted on port 22"], expected: "A management network accessed by the management PC via SSH only.", time: "20 min", checks: ["Router + Switch + PC", "PC connected to switch", "Switch connected to router", "Complete network (4+)"] },
    he: { title: "אבטחת גישה ב-SSH", desc: "הכינו מכשיר ניהול שמגיע לרשת דרך SSH בלבד — ללא Telnet.", objective: "יישום SSH: מפתחות RSA, משתמש מקומי, ו-transport input ssh.", objectives: ["הוסיפו נתב, מתג ו-PC ניהול", "חברו הכל", "הפעילו SSH על הנתב", "בדקו גישה מה-PC"], hints: ["SSH דורש hostname, domain-name ומפתחות RSA", "transport input ssh מונע Telnet", "SSH מוצפן ביציאה 22"], expected: "רשת ניהול שנגישה על ידי מחשב הניהול דרך SSH בלבד.", time: "20 דקות", checks: ["נתב + מתג + PC", "PC מחובר למתג", "מתג מחובר לנתב", "רשת מלאה (4+)"] },
  },
  collision_domains: {
    en: { title: "Collision and Broadcast Domains", desc: "Build a network showing: each switch port is a collision domain, each router interface is a broadcast domain.", objective: "Apply the differences between Hub/Switch/Router effects on domains.", objectives: ["Add two switches, two devices on each", "Add a router connecting the switches", "Identify collision domains", "Test broadcast in each segment"], hints: ["Each switch port is a separate collision domain", "Only the router splits the broadcast domain", "VLAN is a logical split of the broadcast domain"], expected: "A two-segment network with separate broadcast domains and 4 collision domains.", time: "20 min", checks: ["Two switches", "4 PCs", "Router connecting segments", "Devices connected"] },
    he: { title: "תחומי התנגשות ושידור", desc: "בנו רשת המציגה: כל יציאת מתג היא תחום התנגשות, כל ממשק נתב הוא תחום שידור.", objective: "יישום ההבדלים בין Hub/מתג/נתב על תחומים.", objectives: ["הוסיפו שני מתגים, שני מכשירים על כל מתג", "הוסיפו נתב המחבר את המתגים", "זהו תחומי התנגשות", "בדקו שידור בכל מקטע"], hints: ["כל יציאת מתג היא תחום התנגשות עצמאי", "רק הנתב מפצל את תחום השידור", "VLAN הוא חלוקה לוגית של תחום השידור"], expected: "רשת דו-מקטעית עם שני תחומי שידור נפרדים ו-4 תחומי התנגשות.", time: "20 דקות", checks: ["שני מתגים", "4 מחשבים", "נתב מחבר מקטעים", "מכשירים מחוברים"] },
  },

  /* ══════════ صعب (Hard) ══════════ */
  static_routing: {
    en: { title: "Static Routing Setup", desc: "Connect two different networks via two routers and static routes.", objective: "Implement ip route manually between two networks and verify with ping.", objectives: ["Add two routers and connect them", "Add a device network for each router", "Add Static Routes between them", "Test connectivity between networks"], hints: ["Each router needs a route to the other's network", "ip route [dest] [mask] [next-hop]", "Verify with ping after configuration"], expected: "Two networks communicating via correct static routes.", time: "30 min", checks: ["Two routers linked", "4 devices across networks", "Complete network (6+)", "Enough connections (6+)"] },
    he: { title: "הגדרת Static Routing", desc: "חברו שתי רשתות שונות דרך שני נתבים ונתיבים סטטיים.", objective: "יישום ip route ידנית בין שתי רשתות ואימות ב-ping.", objectives: ["הוסיפו שני נתבים וחברו אותם", "הוסיפו רשת מכשירים לכל נתב", "הוסיפו Static Routes ביניהם", "בדקו חיבור בין הרשתות"], hints: ["כל נתב זקוק לנתיב לרשת של השני", "ip route [dest] [mask] [next-hop]", "אמתו ב-ping לאחר ההגדרה"], expected: "שתי רשתות המתקשרות דרך נתיבים סטטיים נכונים.", time: "30 דקות", checks: ["שני נתבים מחוברים", "4 מכשירים ברשתות", "רשת מלאה (6+)", "מספיק חיבורים (6+)"] },
  },
  routing_chain: {
    en: { title: "Three-Router Routing Chain", desc: "Three routers in a row — a packet crosses three hops.", objective: "Read the routing table and trace a packet's path across multiple routers.", objectives: ["Add 3 routers in a row and connect them", "Add a device network at each end", "Configure chain routes", "Trace the packet with Traceroute"], hints: ["Each hop means a MAC change while IP stays", "AD for static route = 1", "ping from end to end is the final test"], expected: "A three-hop chain connecting the two end networks.", time: "35 min", checks: ["3 routers", "Routers linked sequentially", "Devices at both ends", "Complete network (6+)"] },
    he: { title: "שרשרת ניתוב משלושה נתבים", desc: "שלושה נתבים ברצף — חבילה חוצה שלוש דילוגים (Hops).", objective: "קריאת טבלת הניתוב ומעקב נתיב חבילה דרך מספר נתבים.", objectives: ["הוסיפו 3 נתבים ברצף וחברו אותם", "הוסיפו רשת מכשירים בקצוות השרשרת", "הגדירו נתיבי שרשרת", "עקבו אחר החבילה ב-Traceroute"], hints: ["כל דילוג משמעו שינוי MAC עם שמירת IP", "AD לנתיב סטטי = 1", "ping מקצה לקצה הוא המבחן הסופי"], expected: "שרשרת תלת-דילוגית המחברת את רשתות הקצוות.", time: "35 דקות", checks: ["3 נתבים", "נתבים מחוברים ברצף", "מכשירים בשני הקצוות", "רשת מלאה (6+)"] },
  },
  floating_backup: {
    en: { title: "Floating Static Backup Route", desc: "A primary route and a backup route with higher AD between two routers.", objective: "Understand route preference via Administrative Distance and recovery on failure.", objectives: ["Add two routers", "Connect them with two links (primary + backup)", "Add devices for each router", "Set the backup route with AD 200"], hints: ["The route with lower AD wins", "AD 200 is used only when the primary fails", "Two physical links between the routers"], expected: "Two routers with two links: active primary and silent backup.", time: "30 min", checks: ["Two routers", "Two links between them", "Devices on both sides"] },
    he: { title: "נתיב גיבוי Floating Static", desc: "נתיב ראשי ונתיב גיבוי עם AD גבוה יותר בין שני נתבים.", objective: "הבנת העדפת נתיבים דרך Administrative Distance והתאוששות בעת כשל.", objectives: ["הוסיפו שני נתבים", "חברו ביניהם שני קישורים (ראשי + גיבוי)", "הוסיפו מכשירים לכל נתב", "הגדירו נתיב גיבוי עם AD 200"], hints: ["הנתיב עם AD נמוך יותר זוכה", "AD 200 משמש רק כשהראשי נכשל", "שני קישורים פיזיים בין הנתבים"], expected: "שני נתבים עם שני קישורים: ראשי פעיל וגיבוי שקט.", time: "30 דקות", checks: ["שני נתבים", "שני קישורים ביניהם", "מכשירים בשני הצדדים"] },
  },
  ospf_area: {
    en: { title: "Single OSPF Area", desc: "Three routers in Area 0 with Full neighbors and fixed Router-IDs.", objective: "Configure OSPFv2: network with wildcard, passive-interface, and Full neighbors.", objectives: ["Add 3 routers", "Connect them fully (Full Mesh)", "Enable OSPF on interfaces", "Verify Full neighbors"], hints: ["Router-ID prefers highest Loopback", "Wildcard is the inverse of the mask: /24 → 0.0.0.255", "show ip ospf neighbor to verify"], expected: "OSPF neighbors with Full state between three routers.", time: "40 min", checks: ["3 routers", "Enough links (3+)", "End devices connected", "Switches for distribution"] },
    he: { title: "אזור OSPF יחיד", desc: "שלושה נתבים ב-Area 0 עם שכנים Full ו-Router-IDs קבועים.", objective: "הגדרת OSPFv2: network עם wildcard, passive-interface, ושכנים Full.", objectives: ["הוסיפו 3 נתבים", "חברו אותם במלואם (Full Mesh)", "הפעילו OSPF על ממשקים", "אמתו שכנים Full"], hints: ["Router-ID מעדיף Loopback גבוה", "Wildcard הוא ההפך מהמסכה: /24 ← 0.0.0.255", "show ip ospf neighbor לאימות"], expected: "שכני OSPF במצב Full בין שלושה נתבים.", time: "40 דקות", checks: ["3 נתבים", "מספיק קישורים (3+)", "מכשירי קצה מחוברים", "מתגים לחלוקה"] },
  },
  redundant_network: {
    en: { title: "High-Availability Redundant Network", desc: "Design a network with backup paths ensuring no service interruption.", objective: "Apply redundancy: multiple paths with STP and OSPF for automatic recovery.", objectives: ["Add two routers and connect them (backup path)", "Add two+ switches", "Provide more than one path between devices", "Verify automatic recovery"], hints: ["Redundancy = two paths to the same destination", "STP prevents loops in switches", "OSPF reroutes automatically on failure"], expected: "A network with multiple paths exceeding the number of nodes.", time: "35 min", checks: ["Two routers linked", "Two+ switches", "Multiple paths", "Devices connected"] },
    he: { title: "רשת Redundant בזמינות גבוהה", desc: "תכננו רשת עם נתיבי גיבוי המבטיחים אי-הפסקת שירות.", objective: "יישום יתירות: נתיבים מרובים עם STP ו-OSPF להתאוששות אוטומטית.", objectives: ["הוסיפו שני נתבים וחברו אותם (נתיב גיבוי)", "הוסיפו שני מתגים+", "ספקו יותר מנתיב אחד בין מכשירים", "אמתו התאוששות אוטומטית"], hints: ["יתירות = שני נתיבים לאותו יעד", "STP מונע לולאות במתגים", "OSPF מנתב מחדש אוטומטית בעת כשל"], expected: "רשת עם נתיבים מרובים העולים על מספר הצמתים.", time: "35 דקות", checks: ["שני נתבים מחוברים", "שני מתגים+", "נתיבים מרובים", "מכשירים מחוברים"] },
  },
  acl_standard: {
    en: { title: "Standard ACL List", desc: "Deny one network access to another while allowing the rest — near the destination.", objective: "Apply Standard ACL with wildcard, rule ordering, and implicit deny.", objectives: ["Add a router between two networks", "A switch and PC for each network", "Apply a filter list by source", "Verify deny and allow"], hints: ["Standard ACL filters source only", "Placed near the destination", "Each list ends implicitly with deny any"], expected: "A source network denied from the destination network, rest allowed.", time: "30 min", checks: ["Router between networks", "Two switches", "Devices in both networks", "Router connected to both switches"] },
    he: { title: "רשימת ACL סטנדרטית", desc: "מנעו רשת אחת מגישה לאחרת תוך הרשאת השאר — ליד היעד.", objective: "יישום Standard ACL עם wildcard, סדר כללים, ו-implicit deny.", objectives: ["הוסיפו נתב בין שתי רשתות", "מתג ו-PC לכל רשת", "יישמו רשימת סינון לפי מקור", "אמתו מניעה והרשאה"], hints: ["Standard ACL מסנן מקור בלבד", "ממוקם ליד היעד", "כל רשימה מסתיימת ב-implicit deny any"], expected: "רשת מקור מנועה מרשת היעד, השאר מורשה.", time: "30 דקות", checks: ["נתב בין הרשתות", "שני מתגים", "מכשירים בשתי הרשתות", "נתב מחובר לשני המתגים"] },
  },
  firewall_acl: {
    en: { title: "Firewall and ACL Setup", desc: "Protect the internal network from unauthorized external access.", objective: "Apply Extended ACL: source + destination + protocol and port.", objectives: ["Add a Firewall between inside and outside", "Connect it to both networks", "Set deny and allow rules", "Test the rules"], hints: ["The Firewall is placed between the two networks", "Extended ACL near the source", "Don't forget the permit rule for the rest"], expected: "A firewall between two networks with effective filtering rules.", time: "40 min", checks: ["Firewall exists", "Firewall connected to two networks", "Internal network (Switch)", "Complete network (4+)"] },
    he: { title: "הגדרת Firewall ו-ACL", desc: "הגנו על הרשת הפנימית מגישה חיצונית לא מורשית.", objective: "יישום Extended ACL: מקור + יעד + פרוטוקול ויציאה.", objectives: ["הוסיפו Firewall בין פנים לחוץ", "חברו אותו לשתי הרשתות", "הגדירו כללי מניעה והרשאה", "בדקו את הכללים"], hints: ["ה-Firewall ממוקם בין שתי הרשתות", "Extended ACL ליד המקור", "אל תשכחו כלל permit להרשאת השאר"], expected: "חומת אש בין שתי רשתות עם כללי סינון יעילים.", time: "40 דקות", checks: ["Firewall קיים", "Firewall מחובר לשתי רשתות", "רשת פנימית (מתג)", "רשת מלאה (4+)"] },
  },
  nat_static: {
    en: { title: "Static NAT for Public Server", desc: "An internal server needs a fixed 1:1 public address via the router.", objective: "Implement Static NAT: inside/outside and translating one fixed address.", objectives: ["Add an internal server and a switch", "Add a NAT router between inside and outside", "Connect the outside to Cloud", "Set inside/outside"], hints: ["ip nat inside on the internal network interface", "outside on the Internet interface", "show ip nat translations to verify"], expected: "An internal server appearing to the world with a fixed public address.", time: "30 min", checks: ["NAT router", "Internal server connected", "Outside (Cloud) connected to router", "Internal network (Switch)"] },
    he: { title: "NAT סטטי לשרת ציבורי", desc: "שרת פנימי זקוק לכתובת ציבורית קבועה 1:1 דרך הנתב.", objective: "יישום Static NAT: inside/outside ותרגום כתובת אחת קבועה.", objectives: ["הוסיפו שרת פנימי ומתג", "הוסיפו נתב NAT בין פנים לחוץ", "חברו את החוץ ל-Cloud", "הגדירו inside/outside"], hints: ["ip nat inside על ממשק הרשת הפנימית", "outside על ממשק האינטרנט", "show ip nat translations לאימות"], expected: "שרת פנימי הנראה לעולם בכתובת ציבורית קבועה.", time: "30 דקות", checks: ["נתב NAT", "שרת פנימי מחובר", "חוץ (Cloud) מחובר לנתב", "רשת פנימית (מתג)"] },
  },

  /* ══════════ متقدم (Advanced) ══════════ */
  pat_overload: {
    en: { title: "PAT — NAT Overload", desc: "Hundreds of devices sharing one public address via port numbers.", objective: "Implement full PAT: access list and pool via the outgoing interface overload.", objectives: ["Add a switch and 3 internal devices", "Add a PAT router", "Connect the router to the Internet (Cloud)", "Enable overload on the outgoing interface"], hints: ["One address suffices for the entire network via ports", "access-list specifies allowed devices", "interface overload instead of pool"], expected: "A complete network exiting to the Internet via one public address.", time: "40 min", checks: ["PAT router connected to Internet", "3 internal devices", "Internal network connected", "Complete network (6+)"] },
    he: { title: "PAT — NAT Overload", desc: "מאות מכשירים חולקים כתובת ציבורית אחת דרך מספרי יציאות.", objective: "יישום PAT מלא: רשימת גישה ו-pool דרך ממשק היציאה overload.", objectives: ["הוסיפו מתג ו-3 מכשירים פנימיים", "הוסיפו נתב PAT", "חברו את הנתב לאינטרנט (Cloud)", "הפעילו overload על ממשק היציאה"], hints: ["כתובת אחת מספיקה לכל הרשת דרך יציאות", "access-list מציין מכשירים מורשים", "interface overload במקום pool"], expected: "רשת מלאה היוצאת לאינטרנט דרך כתובת ציבורית אחת.", time: "40 דקות", checks: ["נתב PAT מחובר לאינטרנט", "3 מכשירים פנימיים", "הרשת הפנימית מחוברת", "רשת מלאה (6+)"] },
  },
  dmz_setup: {
    en: { title: "DMZ Setup for Servers", desc: "A secure DMZ zone for public servers with internal network isolation.", objective: "Three-zone design: Internet, DMZ, and internal — via a firewall.", objectives: ["Add a central Firewall", "Add two servers in the DMZ", "Add an internal network (Switch + PC)", "Connect the Firewall to the Internet", "Isolate internal from external"], hints: ["DMZ between the Firewall and the Internet", "DMZ servers are reachable from the Internet but not from the internal network", "At least 3 connection points on the firewall"], expected: "A three-zone firewall with two DMZ servers and an isolated internal network.", time: "45 min", checks: ["Central Firewall", "Firewall connected to 3 networks", "Two servers in DMZ", "Internal network (PC)", "Internet connection (Cloud)"] },
    he: { title: "הגדרת DMZ לשרתים", desc: "אזור DMZ מאובטח לשרתים ציבוריים עם בידוד הרשת הפנימית.", objective: "תכנון תלת-אזורי: אינטרנט, DMZ ופנים — דרך חומת אש.", objectives: ["הוסיפו Firewall מרכזי", "הוסיפו שני שרתים ב-DMZ", "הוסיפו רשת פנימית (מתג + PC)", "חברו את ה-Firewall לאינטרנט", "בודדו פנים מחוץ"], hints: ["DMZ בין ה-Firewall לאינטרנט", "שרתי DMZ נגישים מהאינטרנט אך לא מהרשת הפנימית", "לפחות 3 נקודות חיבור על חומת האש"], expected: "חומת אש תלת-אזורית עם שני שרתי DMZ ורשת פנימית מבודדת.", time: "45 דקות", checks: ["Firewall מרכזי", "Firewall מחובר ל-3 רשתות", "שני שרתים ב-DMZ", "רשת פנימית (PC)", "חיבור לאינטרנט (Cloud)"] },
  },
  backbone_network: {
    en: { title: "Enterprise Backbone Network", desc: "A complete hierarchical structure: Core → Distribution → Access for a multi-role company.", objective: "Design the three-tier hierarchical architecture for a large enterprise.", objectives: ["Add a Core Router", "Add 3 distribution switches", "Distribute 6 devices among them", "Add a central server", "Connect the full structure"], hints: ["Core → Distribution → Access hierarchically", "Each distribution switch serves a group of devices", "The central router connects everything"], expected: "A hierarchical enterprise structure fully connected with a central server.", time: "50 min", checks: ["Core Router", "3 distribution switches", "6+ devices", "Central server", "Router connected to switches"] },
    he: { title: "רשת Backbone לארגון", desc: "מבנה היררכי מלא: Core ← Distribution ← Access לחברה רב-תפקידית.", objective: "תכנון ארכיטקטורה היררכית תלת-שכבתית לארגון גדול.", objectives: ["הוסיפו Core Router", "הוסיפו 3 מתגי חלוקה", "חלקו 6 מכשירים עליהם", "הוסיפו שרת מרכזי", "חברו את המבנה המלא"], hints: ["Core ← Distribution ← Access היררכית", "כל מתג חלוקה משרת קבוצת מכשירים", "הנתב המרכזי מחבר הכל"], expected: "מבנה ארגוני היררכי מחובר במלואו עם שרת מרכזי.", time: "50 דקות", checks: ["Core Router", "3 מתגי חלוקה", "6+ מכשירים", "שרת מרכזי", "נתב מחובר למתגים"] },
  },
  enterprise_fortress: {
    en: { title: "Comprehensive Enterprise Fortress", desc: "Combine everything you've learned: NAT + DMZ + ACL + hierarchical structure in one secured network.", objective: "Comprehensive security design: firewall, zones, address translation, and hierarchical distribution.", objectives: ["Add Firewall and NAT router", "Servers in DMZ", "Hierarchical internal network (two switches + 4 devices)", "Connect all to the Internet (Cloud)", "Apply ACL rules at the borders"], hints: ["Start from the outside: Cloud → Firewall → inside", "DMZ for public services only", "Each zone has an independent address range"], expected: "A complete enterprise network with all zones and rules secured.", time: "60 min", checks: ["Firewall + Router together", "DMZ servers", "Internal network (two switches)", "4+ devices", "Internet connection (Cloud)"] },
    he: { title: "מבצר ארגוני מקיף", desc: "שלבו כל מה שלמדתם: NAT + DMZ + ACL + מבנה היררכי ברשת אחת מאובטחת.", objective: "תכנון אבטחתי מקיף: חומת אש, אזורים, תרגום כתובות וחלוקה היררכית.", objectives: ["הוסיפו Firewall ונתב NAT", "שרתים ב-DMZ", "רשת פנימית היררכית (שני מתגים + 4 מכשירים)", "חברו הכל לאינטרנט (Cloud)", "יישמו כללי ACL בגבולות"], hints: ["התחילו מבחוץ: Cloud ← Firewall ← פנימה", "DMZ לשירותים ציבוריים בלבד", "לכל אזור טווח כתובות עצמאי"], expected: "רשת ארגונית מאובטחת מלאת אזורים וכללים.", time: "60 דקות", checks: ["Firewall + נתב יחד", "שרתי DMZ", "רשת פנימית (שני מתגים)", "4+ מכשירים", "חיבור לאינטרנט (Cloud)"] },
  },
};

/** يُرجع نسخة السيناريو باللغة الحالية — مع fallback للعربية (المصدر) */
export function localizeScenario(scenario) {
  if (!scenario) return scenario;
  const lang = getLang();
  if (lang === "ar" || !I18N[scenario.id]) return scenario;
  const tr = I18N[scenario.id][lang];
  if (!tr) return scenario;
  return {
    ...scenario,
    title: tr.title || scenario.title,
    desc: tr.desc || scenario.desc,
    objective: tr.objective || scenario.objective,
    objectives: tr.objectives || scenario.objectives,
    hints: tr.hints || scenario.hints,
    expected: tr.expected || scenario.expected,
    time: tr.time || scenario.time,
    // lab() تزيل checks من الكائن وتخزنها في closure — نستخدم tasks الموجودة فعلاً
    tasks: tr.checks || scenario.tasks,
    checks: scenario.tasks?.map((taskLabel, i) => ({ label: tr.checks?.[i] || taskLabel })),
  };
}

/** يُرجع عنوان السيناريو باللغة الحالية */
export function scenarioTitle(scenario) {
  const lang = getLang();
  if (lang === "ar" || !scenario) return scenario?.title || "";
  return I18N[scenario?.id]?.[lang]?.title || scenario?.title || "";
}

/** يُرجع وصف السيناريو باللغة الحالية */
export function scenarioDesc(scenario) {
  const lang = getLang();
  if (lang === "ar" || !scenario) return scenario?.desc || "";
  return I18N[scenario?.id]?.[lang]?.desc || scenario?.desc || "";
}

/** يُرجع نص رسالة النجاح/الفشل باللغة الحالية */
export function scenarioFeedback(passed) {
  const lang = getLang();
  const msgs = {
    ar: {
      pass: "أحسنت! أنجزت مهام السيناريو بنجاح.",
      fail: "لم تكتمل جميع المهام بعد — راجع الأهداف غير المنجزة وحاول مجدداً.",
    },
    en: {
      pass: "Well done! You completed the scenario tasks successfully.",
      fail: "Not all tasks are complete yet — review the unmet objectives and try again.",
    },
    he: {
      pass: "כל הכבוד! השלמת את משימות התרחיש בהצלחה.",
      fail: "לא כל המשימות הושלמו — סקרו את המטרות שלא הושגו ונסו שוב.",
    },
  };
  return (msgs[lang] || msgs.ar)[passed ? "pass" : "fail"];
}